//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inPurchase
    {
        public long IDPurchase { get; set; }
        public string IDFaktur { get; set; }
        public int IDPartner { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    }
}
