//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Expend
    {
        public long IDExpend { get; set; }
        public string IDFaktur { get; set; }
        public string SupplierName { get; set; }
        public string PhoneNumber { get; set; }
        public decimal Amount { get; set; }
        public int IDSupplier { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public int IDCampaign { get; set; }
        public string CampaignName { get; set; }
    }
}
