//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExpendDetail
    {
        public long IDDetail { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Size { get; set; }
        public int Volume { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public long IDExpend { get; set; }
        public int IDProduct { get; set; }
    }
}
